
project_id = "pfraresupodbfeggrwiy"

[api]
enabled = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.optimize-route]
verify_jwt = true
