
project_id = "pfraresupodbfeggrwiy"

[api]
enabled = true
url = "https://pfraresupodbfeggrwiy.supabase.co"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
