// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfraresupodbfeggrwiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcmFyZXN1cG9kYmZlZ2dyd2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzQzOTcsImV4cCI6MjA1NTc1MDM5N30.9scT8uWGZPGXnmV1vMFN0Pq-ZS97Sw1e-wzIgyy0HuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);